[package]
name = "gene_game"
version = "0.1.0"
authors = ["RipleyTom <RipleyTom@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
num-traits = "0.2.8"
num-derive = "0.2.5"
sdl2 = "0.32.2"
